import {
	Car,
	Truck,
	Bike,
	MapPin,
	Route,
	ArrowUp,
	CloudRain,
	TrafficCone,
	Bell,
	Settings,
	Crosshair,
	Layers,
	Search,
	X,
	Play,
	Pause,
	Volume2,
	Plus,
	ChevronDown,
	Trash2,
	ArrowLeftRight,
	Circle,
	BriefcaseBusiness,
	Landmark,
	ShoppingBag,
	Clock,
	Hospital,
	Waves,
	GraduationCap,
	Store,
	Plane,
	Lightbulb,
	Flag,
	CornerUpLeft,
	CornerUpRight,
	ArrowRight,
	Zap,
	WifiOff,
	Navigation,
	LoaderCircle
} from '@lucide/svelte';

export const icons = {
	suv: Car,
	truck: Truck,
	motorcycle: Bike,
	bicycle: Bike,
	pin: MapPin,
	route: Route,
	arrow: ArrowUp,
	car: Car,
	rain: CloudRain,
	traffic: TrafficCone,
	bell: Bell,
	settings: Settings,
	target: Crosshair,
	layers: Layers,
	search: Search,
	close: X,
	play: Play,
	pause: Pause,
	sound: Volume2,
	plus: Plus,
	chevron: ChevronDown,
	trash: Trash2,
	swap: ArrowLeftRight,
	circle: Circle,
	work: BriefcaseBusiness,
	landmark: Landmark,
	shopping: ShoppingBag,
	clock: Clock,
	hospital: Hospital,
	waves: Waves,
	school: GraduationCap,
	store: Store,
	plane: Plane,
	lightbulb: Lightbulb,
	flag: Flag,
	left: CornerUpLeft,
	right: CornerUpRight,
	forward: ArrowRight,
	zap: Zap,
	offline: WifiOff,
	navigation: Navigation,
	loader: LoaderCircle
};
export type IconName = keyof typeof icons;
